import {
  MD3LightTheme,
  MD3DarkTheme,
  useTheme,
} from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';
import { brand, light, dark } from './colors';

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 6,
  colors: {
    ...MD3LightTheme.colors,
    primary: brand.teal,
    onPrimary: '#FFFFFF',
    primaryContainer: brand.tealLight,
    onPrimaryContainer: '#FFFFFF',
    secondary: brand.gold,
    onSecondary: '#2D2D2D',
    secondaryContainer: brand.goldLight,
    onSecondaryContainer: '#2D2D2D',
    tertiary: brand.tealDark,
    onTertiary: '#FFFFFF',
    background: light.background,
    onBackground: light.text,
    surface: light.surface,
    onSurface: light.text,
    surfaceVariant: light.surfaceVariant,
    onSurfaceVariant: light.textSecondary,
    outline: light.outline,
    outlineVariant: light.divider,
    error: light.error,
    onError: '#FFFFFF',
    errorContainer: light.errorContainer,
    onErrorContainer: light.error,
    inverseSurface: dark.surface,
    inverseOnSurface: dark.text,
    inversePrimary: brand.goldLight,
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: light.surface,
      level2: light.surfaceVariant,
      level3: light.surfaceVariant,
      level4: light.surfaceVariant,
      level5: light.surfaceVariant,
    },
    surfaceDisabled: light.surfaceVariant,
    onSurfaceDisabled: light.textMuted,
    backdrop: 'rgba(45, 45, 45, 0.4)',
    shadow: 'rgba(0, 0, 0, 0.08)',
    scrim: 'rgba(0, 0, 0, 0.3)',
  },
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: 6,
  colors: {
    ...MD3DarkTheme.colors,
    primary: brand.tealLight,
    onPrimary: '#FFFFFF',
    primaryContainer: brand.teal,
    onPrimaryContainer: '#FFFFFF',
    secondary: brand.gold,
    onSecondary: '#2D2D2D',
    secondaryContainer: brand.goldDark,
    onSecondaryContainer: '#FFFFFF',
    tertiary: brand.tealLight,
    onTertiary: '#FFFFFF',
    background: dark.background,
    onBackground: dark.text,
    surface: dark.surface,
    onSurface: dark.text,
    surfaceVariant: dark.surfaceVariant,
    onSurfaceVariant: dark.textSecondary,
    outline: dark.outline,
    outlineVariant: dark.divider,
    error: dark.error,
    onError: '#FFFFFF',
    errorContainer: dark.errorContainer,
    onErrorContainer: dark.error,
    inverseSurface: light.surface,
    inverseOnSurface: light.text,
    inversePrimary: brand.teal,
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level0: 'transparent',
      level1: dark.surface,
      level2: dark.surfaceVariant,
      level3: dark.surfaceVariant,
      level4: dark.surfaceVariant,
      level5: dark.surfaceVariant,
    },
    surfaceDisabled: dark.surfaceVariant,
    onSurfaceDisabled: dark.textMuted,
    backdrop: 'rgba(0, 0, 0, 0.6)',
    shadow: 'rgba(0, 0, 0, 0.3)',
    scrim: 'rgba(0, 0, 0, 0.5)',
  },
};

export function useAppTheme() {
  return useTheme<MD3Theme>();
}
